---
services:
  space-station:
    build: .
    container_name: ss14-docker
    restart: unless-stopped
    ports:
      - "1212:1212/udp"
      - "1212:1212/tcp"
    volumes:
      - ss14:/SS14.Watchdog/SS14.Watchdog/bin/Release
    environment:
      - DOTNET_CLI_HOME=/tmp

volumes:
  ss14:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/ss14-docker/ss14
